name: ci-unit-tests

on:
  push:
    branches: [ "main" ] # Run on pushes to the main branch
  pull_request:
    branches: [ "main" ] # Run on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - uses: actions/checkout@v4 # Checkout code

    - name: Set up Go
      uses: actions/setup-go@v4 # Set up Go environment
      with:
        go-version: '1.21.0'

    - name: Cache Go Modules
      uses: actions/cache@v3 # Cache dependencies
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run: go build -v ./... # Build the project

    - name: Run Unit Tests
      run: make unit-test # Run unit tests
