name: Release to Docker Hub

on:
  workflow_run:
    workflows:
      - "ci-unit-tests" # Unit test workflow
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    # Ensure both workflows completed successfully before proceeding
    if: >
      ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.0"

      # Install dependencies
      - name: Install Dependencies
        run: |
          go mod tidy
          go mod vendor

      # Debugging step to inspect environment
      - name: Debug Log
        run: |
          echo "Current directory:"
          pwd
          echo "List files in workspace:"
          ls -al
          echo "Environment variables:"
          env

      # Build subscription binary using Makefile
      - name: Build Subscription Binary
        run: make build_subscription_service

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/rental-subscription-service:1.0.0 .

      # Push Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/rental-subscription-service:1.0.0
